/*
main.cpp written by Jim bailey
altered by Christy Wear (Ganger) to add header. "Triangle.h"
Triangle.h and Triangle.cpp Generated by codeblocks class template.
Edited, written by christy  Wear (ganger).
Version 1
3/28/2019
Lab 6 - Triangle Class Lab
CIS 162C++
*/

#include "Triangle.h"
#include <iostream>

using namespace std;
Triangle::Triangle()
{
    setA(3);
    setB(4);
    setC(5);
}

Triangle::Triangle(int inc_side_1, int inc_side_2, int inc_side_3)
{
    setA(inc_side_1);
    setB(inc_side_2);
    setC(inc_side_3);
}

void Triangle::setA(int inc_side_1)
{
    side_1 = inc_side_1;
}

void Triangle::setB(int inc_side_2)
{
    side_2 = inc_side_2;
}

void Triangle::setC(int inc_side_3)
{
    side_3 = inc_side_3;
}

int Triangle::getA()
{
    return side_1;
}

int Triangle::getB()
{
    return side_2;
}

int Triangle::getC()
{
    return side_3;
}

bool Triangle::isEquilateral()
{
    if(side_1 == side_2 && side_1 == side_3 && side_2 == side_3)
        return true;
    else
        return false;
}

bool Triangle::isScalene()
{
    if(side_1 != side_2 && side_1 != side_3 && side_2 != side_3)
        return true;
    else
        return false;
}

bool Triangle::isIsosceles()
{
    if ((side_1 == side_2) || (side_1 == side_3) || (side_2 == side_3))
            return true;
    else
        return false;
}

bool Triangle::isRight()
{
    if ((((side_1^2) + (side_2^2)) == (side_3^2)) ||
        (((side_2^2) + (side_3^2)) == (side_1^2)) ||
        (((side_3^2) + (side_1^2)) == (side_2^2)))
            return true;
    else
        return false;
}
