/*
main.cpp written by Jim bailey
altered by Christy Wear (Ganger) to add header. "Triangle.h"
Triangle.h and Triangle.cpp Generated by codeblocks class template.
Edited, written by christy  Wear (ganger).
Version 1
3/28/2019
Lab 6 - Triangle Class Lab
CIS 162C++
*/

#ifndef TRIANGLE_H
#define TRIANGLE_H


class Triangle
{
    public:
        Triangle();
        Triangle(int, int, int);
        void setA(int);
        void setB(int);
        void setC(int);
        int getA();
        int getB();
        int getC();
        bool isEquilateral();
        bool isScalene();
        bool isIsosceles();
        bool isRight();

    protected:

    private:
        int side_1;
        int side_2;
        int side_3;
};

#endif // TRIANGLE_H
